INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (1,'UNITED_STATES','74.0° W, 40.42° N', '/defense/images/united_states_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (2,'UNITED_KINGDOM','0.1° E, 51.30° N', '/defense/images/united_kingdom_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (3,'GERMANY','13.25° E, 52.30° N', '/defense/images/germany_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (4,'FRANCE','2.20° E, 48.51° N', '/defense/images/france_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (5,'JAPAN','139.44° E, 35.41° N', '/defense/images/japan_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (6,'SOUTH_KOREA','126.58° E, 37.33° N', '/defense/images/south_korea_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (7,'SPAIN',' 3.45° W, 40.25° N', '/defense/images/spain_map.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (8,'AUSTRALIA','149.07° E, 35.17° S', '/defense/images/australia_map.jpg');