TRUNCATE TABLE TBL_ORDER_ITEM RESTART IDENTITY AND COMMIT NO CHECK
TRUNCATE TABLE TBL_ORDER RESTART IDENTITY AND COMMIT NO CHECK
TRUNCATE TABLE TBL_CART RESTART IDENTITY AND COMMIT NO CHECK
TRUNCATE TABLE TBL_ITEM RESTART IDENTITY AND COMMIT NO CHECK
TRUNCATE TABLE TBL_CATEGORY RESTART IDENTITY AND COMMIT NO CHECK