INSERT INTO PUBLIC.PUBLIC.TBL_SHIPPING (ID,SHIPPING_TYPE) VALUES (1,'STANDARD_SHIPPING');
INSERT INTO PUBLIC.PUBLIC.TBL_SHIPPING (ID,SHIPPING_TYPE) VALUES (2,'RUSH_SHIPPING');
INSERT INTO PUBLIC.PUBLIC.TBL_SHIPPING (ID,SHIPPING_TYPE) VALUES (3,'NEXT_DAY_SHIPPING');