INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (1,'MERCURY','19.90° E, 50.47° N', '/aerospace/images/space-map@0.25-Mercu.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (2,'VENUS','71.05° W, 42.20° N', '/aerospace/images/space-map@0.25x-Ven.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (3,'EARTH','55.40° W, 52.13° N', '/aerospace/images/space-map@0.25x-Ear.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (4,'MARS','65.10° W, 42.136° N', '/aerospace/images/space-map@0.25x-Mar.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (5,'JUPITER','35.42° W, 12.16° N', '/aerospace/images/space-map@0.25x-Jup.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (6,'SATURN','45.47° W, 62.33° N', '/aerospace/images/space-map@0.25x-Sat.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (7,'URANUS','45.30° W, 22.13° N', '/aerospace/images/space-map@0.25x-Ura.jpg');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (8,'NEPTUNE','45.30° W, 22.13° N', '/aerospace/images/space-map@0.25x-Nep.jpg');