INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (1,10);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (2,11);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (3,12);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (4,13);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (5,20);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (6,21);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (7,22);
INSERT INTO PUBLIC.PUBLIC.TBL_ITEM_INVENTORY (ITEM_ID,IN_STOCK) VALUES (8,23);