INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (1,'LOCATION_1','29.90° E, 54.41° N', '/outdoor/images/generic-map-1.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (2,'LOCATION_2','19.90° E, 50.47° N', '/outdoor/images/generic-map-2.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (3,'LOCATION_3','12.21° E, 50.42° N', '/outdoor/images/generic-map-3.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (4,'LOCATION_4','59.90° W, 50.47° S', '/outdoor/images/generic-map-4.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (5,'LOCATION_5','09.90° E, 70.47° N', '/outdoor/images/generic-map-5.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (6,'LOCATION_6','49.50° E, 30.47° S', '/outdoor/images/generic-map-6.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (7,'LOCATION_7','16.20° E, 52.38° N', '/outdoor/images/generic-map-7.png');
INSERT INTO PUBLIC.PUBLIC.TBL_LOCATION (ID,REGION,LOCATION_INFO,LOCATION_IMAGE) VALUES (8,'LOCATION_8','44.20° E, 25.17° N', '/outdoor/images/generic-map-8.png');
